"""empty message

Revision ID: 1301dd2b9ce9
Revises: 412912d023f4
Create Date: 2015-12-07 18:53:15.354948

"""

# revision identifiers, used by Alembic.
revision = '1301dd2b9ce9'
down_revision = '412912d023f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('display_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], [u'customer.id'], name=u'slot_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'slot_pkey')
    )
    ### end Alembic commands ###
