"""empty message

Revision ID: 14930825c5da
Revises: 541cae7cd330
Create Date: 2016-01-14 15:59:42.269237

"""

# revision identifiers, used by Alembic.
revision = '14930825c5da'
down_revision = '541cae7cd330'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_email', sa.Column('for_shop_id', sa.Integer(), nullable=True))
    op.add_column('sent_email', sa.Column('opened_timestamp', sa.DateTime(), nullable=True))
    op.add_column('sent_email', sa.Column('tracking_pixel_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sent_email', 'shop', ['for_shop_id'], ['id'])
    op.drop_column('sent_email', 'traceback')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_email', sa.Column('traceback', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sent_email', type_='foreignkey')
    op.drop_column('sent_email', 'tracking_pixel_id')
    op.drop_column('sent_email', 'opened_timestamp')
    op.drop_column('sent_email', 'for_shop_id')
    ### end Alembic commands ###
