"""empty message

Revision ID: 1ac78e57fd0b
Revises: 24cd50d944b6
Create Date: 2016-03-01 17:40:24.949932

"""

# revision identifiers, used by Alembic.
revision = '1ac78e57fd0b'
down_revision = '24cd50d944b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscription', 'shop', ['shop_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'shop_id')
    ### end Alembic commands ###
