"""empty message

Revision ID: 1ce2ef8dede8
Revises: 407f3004be4e
Create Date: 2016-02-19 14:39:25.008736

"""

# revision identifiers, used by Alembic.
revision = '1ce2ef8dede8'
down_revision = '407f3004be4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('next_action', sa.Column('completed_ts', sa.DateTime(), nullable=True))
    op.add_column('next_action', sa.Column('is_completed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('next_action', 'is_completed')
    op.drop_column('next_action', 'completed_ts')
    ### end Alembic commands ###
