"""empty message

Revision ID: 1f0734dae42d
Revises: 484b4b0682f8
Create Date: 2016-03-01 11:33:25.170737

"""

# revision identifiers, used by Alembic.
revision = '1f0734dae42d'
down_revision = '484b4b0682f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'trialed_for')
    op.add_column('shop', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('subscription', sa.Column('trialed_for', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'trialed_for')
    op.drop_column('shop', 'active')
    op.add_column('customer', sa.Column('trialed_for', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
