"""empty message

Revision ID: 1fff6bc08c44
Revises: 1ce2ef8dede8
Create Date: 2016-02-27 12:17:15.312726

"""

# revision identifiers, used by Alembic.
revision = '1fff6bc08c44'
down_revision = '1ce2ef8dede8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_legacy', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_legacy')
    ### end Alembic commands ###
