"""empty message

Revision ID: 230e683fe87
Revises: c13926568c4
Create Date: 2015-12-01 13:09:48.836925

"""

# revision identifiers, used by Alembic.
revision = '230e683fe87'
down_revision = 'c13926568c4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'order_task_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'delivery_timestamp')
    op.drop_column('order', 'to_deliver_timestamp')
    op.drop_column('order', 'task_id')
    op.add_column('task', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'order', ['order_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'order_id')
    op.add_column('order', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('to_deliver_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('delivery_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'order_task_id_fkey', 'order', 'task', ['task_id'], ['id'])
    ### end Alembic commands ###
