"""empty message

Revision ID: 233339b13c28
Revises: 55d5b90482a4
Create Date: 2016-01-21 16:26:25.133177

"""

# revision identifiers, used by Alembic.
revision = '233339b13c28'
down_revision = '55d5b90482a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unsubscribe_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('unsubscribed', sa.Boolean(), nullable=True))
    op.add_column('user_legacy', sa.Column('unsubscribe_token', sa.String(), nullable=True))
    op.add_column('user_legacy', sa.Column('unsubscribed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_legacy', 'unsubscribed')
    op.drop_column('user_legacy', 'unsubscribe_token')
    op.drop_column('user', 'unsubscribed')
    op.drop_column('user', 'unsubscribe_token')
    ### end Alembic commands ###
