"""empty message

Revision ID: 24cd50d944b6
Revises: 1f0734dae42d
Create Date: 2016-03-01 15:03:54.599834

"""

# revision identifiers, used by Alembic.
revision = '24cd50d944b6'
down_revision = '1f0734dae42d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_legacy', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_legacy')
    ### end Alembic commands ###
