"""empty message

Revision ID: 24d04330e489
Revises: 41b92da7f24d
Create Date: 2015-11-24 15:20:48.401413

"""

# revision identifiers, used by Alembic.
revision = '24d04330e489'
down_revision = '41b92da7f24d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('display_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot', 'display_url')
    ### end Alembic commands ###
