"""empty message

Revision ID: 289a1a34f2fd
Revises: 3c36b2b7c43
Create Date: 2015-11-29 18:50:36.731122

"""

# revision identifiers, used by Alembic.
revision = '289a1a34f2fd'
down_revision = '3c36b2b7c43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_feature')
    ### end Alembic commands ###
