"""empty message

Revision ID: 299c5b2c28ac
Revises: None
Create Date: 2015-11-21 16:25:21.799440

"""

# revision identifiers, used by Alembic.
revision = '299c5b2c28ac'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_legacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_shop_owner', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'order', sa.Column('user_legacy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'user_legacy', ['user_legacy_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column(u'order', 'user_legacy_id')
    op.drop_table('user_legacy')
    ### end Alembic commands ###
