"""empty message

Revision ID: 2bdd21038fa7
Revises: 32240be95484
Create Date: 2015-11-30 12:50:12.334738

"""

# revision identifiers, used by Alembic.
revision = '2bdd21038fa7'
down_revision = '32240be95484'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('click_count', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('is_public', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_public')
    op.drop_column('question', 'click_count')
    ### end Alembic commands ###
