"""empty message

Revision ID: 35e6a98fd332
Revises: 5417de32f50d
Create Date: 2015-11-30 19:32:15.286231

"""

# revision identifiers, used by Alembic.
revision = '35e6a98fd332'
down_revision = '5417de32f50d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celery_uuid', sa.String(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('kwargs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'order', sa.Column('ttask_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'task', ['ttask_id'], ['id'])
    op.drop_column(u'order', 'task_status')
    op.drop_column(u'order', 'task_eta')
    op.drop_column(u'order', 'task_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'order', sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'order', sa.Column('task_eta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column(u'order', sa.Column('task_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column(u'order', 'ttask_id')
    op.drop_table('task')
    ### end Alembic commands ###
