"""empty message

Revision ID: 3c36b2b7c43
Revises: 24d04330e489
Create Date: 2015-11-24 20:42:56.536910

"""

# revision identifiers, used by Alembic.
revision = '3c36b2b7c43'
down_revision = '24d04330e489'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_request', sa.Column('to_user_legacy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review_request', 'user_legacy', ['to_user_legacy_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_request', type_='foreignkey')
    op.drop_column('review_request', 'to_user_legacy_id')
    ### end Alembic commands ###
