"""empty message

Revision ID: 3d9b31016f13
Revises: 233339b13c28
Create Date: 2016-02-02 18:29:12.611409

"""

# revision identifiers, used by Alembic.
revision = '3d9b31016f13'
down_revision = '233339b13c28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('review', sa.Column('deleted_ts', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'deleted_ts')
    op.drop_column('review', 'deleted')
    ### end Alembic commands ###
