"""empty message

Revision ID: 3de65ef05d34
Revises: 1301dd2b9ce9
Create Date: 2016-01-09 18:46:26.665117

"""

# revision identifiers, used by Alembic.
revision = '3de65ef05d34'
down_revision = '1301dd2b9ce9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('recipients', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('template_ctx', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('traceback', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_email')
    ### end Alembic commands ###
