"""empty message

Revision ID: 3efb17d5c897
Revises: 513b9123d680
Create Date: 2015-11-23 18:48:49.490238

"""

# revision identifiers, used by Alembic.
revision = '3efb17d5c897'
down_revision = '513b9123d680'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('last4', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'last4')
    ### end Alembic commands ###
