"""empty message

Revision ID: 412912d023f4
Revises: 230e683fe87
Create Date: 2015-12-02 20:39:31.417986

"""

# revision identifiers, used by Alembic.
revision = '412912d023f4'
down_revision = '230e683fe87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_variant_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_variant')
    ### end Alembic commands ###
