"""empty message

Revision ID: 41b92da7f24d
Revises: 478eac9e87da
Create Date: 2015-11-24 15:07:03.370132

"""

# revision identifiers, used by Alembic.
revision = '41b92da7f24d'
down_revision = '478eac9e87da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'slot_shop_id_fkey', 'slot', type_='foreignkey')
    op.create_foreign_key(None, 'slot', 'customer', ['customer_id'], ['id'])
    op.drop_column('slot', 'shop_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.create_foreign_key(u'slot_shop_id_fkey', 'slot', 'shop', ['shop_id'], ['id'])
    op.drop_column('slot', 'customer_id')
    ### end Alembic commands ###
