"""empty message

Revision ID: 434989102fbf
Revises: 14930825c5da
Create Date: 2016-01-14 16:10:07.679324

"""

# revision identifiers, used by Alembic.
revision = '434989102fbf'
down_revision = '14930825c5da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_request', sa.Column('opened_timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_request', 'opened_timestamp')
    ### end Alembic commands ###
