"""empty message

Revision ID: 478eac9e87da
Revises: 3efb17d5c897
Create Date: 2015-11-24 14:03:02.621589

"""

# revision identifiers, used by Alembic.
revision = '478eac9e87da'
down_revision = '3efb17d5c897'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'shop', sa.Column('image_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'shop', 'image_url')
    op.drop_table('slot')
    ### end Alembic commands ###
