"""empty message

Revision ID: 484b4b0682f8
Revises: 1ce2ef8dede8
Create Date: 2016-02-29 19:17:19.161651

"""

# revision identifiers, used by Alembic.
revision = '484b4b0682f8'
down_revision = '1ce2ef8dede8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('trialed_for', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'trialed_for')
    ### end Alembic commands ###
