"""empty message

Revision ID: 53326beb4fe7
Revises: 3d9b31016f13
Create Date: 2016-02-11 18:49:53.045610

"""

# revision identifiers, used by Alembic.
revision = '53326beb4fe7'
down_revision = '3d9b31016f13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_referer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('q', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'review_feature', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review_feature', 'user', ['user_id'], ['id'])
    op.drop_column(u'review_feature', 'action')
    op.drop_column(u'review_like', 'action')
    op.drop_column(u'review_report', 'action')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'review_report', sa.Column('action', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'review_like', sa.Column('action', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'review_feature', sa.Column('action', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'review_feature', type_='foreignkey')
    op.drop_column(u'review_feature', 'user_id')
    op.drop_table('review_share')
    op.drop_table('url_referer')
    ### end Alembic commands ###
