"""empty message

Revision ID: 541cae7cd330
Revises: 3de65ef05d34
Create Date: 2016-01-10 18:40:20.617593

"""

# revision identifiers, used by Alembic.
revision = '541cae7cd330'
down_revision = '3de65ef05d34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_legacy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'user_legacy', ['user_legacy_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'user_legacy_id')
    ### end Alembic commands ###
