"""empty message

Revision ID: 58c983f27bf
Revises: 46518b348ec0
Create Date: 2016-04-12 14:03:35.156445

"""

# revision identifiers, used by Alembic.
revision = '58c983f27bf'
down_revision = '46518b348ec0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'active')
    ### end Alembic commands ###
