"""empty message

Revision ID: c13926568c4
Revises: 35e6a98fd332
Create Date: 2015-11-30 19:32:29.288330

"""

# revision identifiers, used by Alembic.
revision = 'c13926568c4'
down_revision = '35e6a98fd332'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('task_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'order_ttask_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'task', ['task_id'], ['id'])
    op.drop_column('order', 'ttask_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('ttask_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(u'order_ttask_id_fkey', 'order', 'task', ['ttask_id'], ['id'])
    op.drop_column('order', 'task_id')
    ### end Alembic commands ###
